const Map<String, String> enUs = {
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.save': 'Save',
  'nav.home': 'Home',
  'nav.booking': 'Booking',
  'nav.wallet': 'Wallet',
  'nav.notification': 'Notifications',
  'nav.profile': 'Profile',
  'profile.emailNotUpdated': 'Email not updated',
  'profile.personalInfo': 'PERSONAL INFORMATION',
  'profile.fullName': 'Full name',
  'profile.phone': 'Phone number',
  'profile.email': 'Email address',
  'profile.notUpdated': 'Not updated',
  'profile.myActivities': 'MY ACTIVITIES',
  'profile.bookingHistory': 'Booking history',
  'profile.mapLocation': 'Badminton facility location',
  'profile.preferences': 'PREFERENCES',
  'profile.darkMode': 'Dark mode',
  'profile.language': 'Language',
  'profile.vietnameseShort': 'Vietnamese',
  'profile.englishShort': 'English',
  'profile.security': 'SECURITY',
  'profile.changePassword': 'Change password',
  'profile.logout': 'Sign out',
  'profile.logoutConfirm': 'Are you sure you want to sign out?',
  'profile.editInfo': 'Update personal information',
  'profile.passwordConfirmTitle': 'Confirm password',
  'profile.currentPassword': 'Current password',
  'home.greeting': 'Hello, @name',
  'home.defaultName': 'you',
  'home.bannerTitle': 'Book fast\nPlay today!',
  'home.bookNow': 'Book now',
  'home.priceTitle': 'Court pricing',
  'home.court': 'Court',
  'home.time': 'Time',
  'home.fixed': 'Fixed',
  'home.account': 'Account',
  'home.guest': 'Guest',
  'booking.oneTime': 'One-time booking',
  'booking.fixed': 'Fixed schedule',
  'notification.title': 'Notifications',
  'notification.markAllRead': 'Mark all read',
  'notification.empty': 'You do not have any notifications yet',
  'notification.end': 'You have seen all notifications for today!',
  'notification.loadError': 'Could not load notifications.',
  'notification.tab.booking': 'Booking',
  'notification.tab.payment': 'Payment',
  'notification.tab.system': 'System',
  'history.title': 'Booking history',
  'history.loadErrorTitle': 'Could not load data',
  'history.tab.all': 'All',
  'history.tab.booked': 'Booked',
  'history.tab.completed': 'Completed',
  'history.tab.cancelled': 'Cancelled',
  'history.tab.contracts': 'Contracts',
  'paymentSuccess.title': 'Booking successful!',
  'paymentSuccess.bookingCode': 'Booking code: #@code',
  'paymentSuccess.date': 'Date',
  'paymentSuccess.time': 'Time',
  'paymentSuccess.home': 'Go Home',
  'paymentSuccess.history': 'View Orders',
  'wallet.title': 'My wallet',
};
