const Map<String, String> viVn = {
  'common.cancel': 'Hủy',
  'common.confirm': 'Xác nhận',
  'common.save': 'Lưu',
  'nav.home': 'Trang chủ',
  'nav.booking': 'Đặt sân',
  'nav.wallet': 'Ví',
  'nav.notification': 'Thông báo',
  'nav.profile': 'Hồ sơ',
  'profile.emailNotUpdated': 'Chưa cập nhật email',
  'profile.personalInfo': 'THÔNG TIN CÁ NHÂN',
  'profile.fullName': 'Họ và tên',
  'profile.phone': 'Số điện thoại',
  'profile.email': 'Địa chỉ email',
  'profile.notUpdated': 'Chưa cập nhật',
  'profile.myActivities': 'HOẠT ĐỘNG CỦA TÔI',
  'profile.bookingHistory': 'Lịch sử đặt sân',
  'profile.mapLocation': 'Vị trí cơ sở cầu lông',
  'profile.preferences': 'SỞ THÍCH',
  'profile.darkMode': 'Chế độ tối',
  'profile.language': 'Ngôn ngữ',
  'profile.vietnameseShort': 'Tiếng Việt',
  'profile.englishShort': 'Tiếng Anh',
  'profile.security': 'BẢO VỆ',
  'profile.changePassword': 'Thay đổi mật khẩu',
  'profile.logout': 'Đăng xuất',
  'profile.logoutConfirm':
      'Bạn có chắc chắn muốn đăng xuất khỏi tài khoản không?',
  'profile.editInfo': 'Cập nhật thông tin cá nhân',
  'profile.passwordConfirmTitle': 'Xác thực mật khẩu',
  'profile.currentPassword': 'Mật khẩu hiện tại',
  'home.greeting': 'Xin chào, @name',
  'home.defaultName': 'bạn',
  'home.bannerTitle': 'Đặt sân nhanh\nChơi ngay hôm nay!',
  'home.bookNow': 'Đặt sân ngay',
  'home.priceTitle': 'Bảng giá sân',
  'home.court': 'Sân',
  'home.fixed': 'Cố định',
  'home.account': 'Tài khoản',
  'home.guest': 'Vãng lai',
  'booking.oneTime': 'Đặt sân lẻ',
  'booking.fixed': 'Đặt lịch cố định',
  'notification.title': 'Thông báo',
  'notification.markAllRead': 'Đọc tất cả',
  'notification.empty': 'Bạn chưa có thông báo nào',
  'notification.end': 'Bạn đã xem hết thông báo hôm nay!',
  'notification.loadError': 'Không tải được thông báo.',
  'notification.tab.booking': 'Đặt sân',
  'notification.tab.payment': 'Thanh toán',
  'notification.tab.system': 'Hệ thống',
  'history.title': 'Lịch sử đặt sân',
  'history.loadErrorTitle': 'Không tải được dữ liệu',
  'history.tab.all': 'Tất cả',
  'history.tab.booked': 'Đã đặt',
  'history.tab.completed': 'Đã kết thúc',
  'history.tab.cancelled': 'Đã hủy',
  'paymentSuccess.title': 'Đặt sân thành công!',
  'paymentSuccess.bookingCode': 'Mã đặt chỗ: #@code',
  'paymentSuccess.date': 'Ngày',
  'paymentSuccess.time': 'Thời gian',
  'paymentSuccess.home': 'Về Trang Chủ',
  'paymentSuccess.history': 'Xem Đơn Hàng',
  'wallet.title': 'Ví của tôi',
};
