name: badminton
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  get:
  cupertino_icons: ^1.0.8
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  http: ^1.2.2
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface:

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
