// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRTosm3a2I9-QXQwACmjERgk1gMYVU1gI',
    appId: '1:166231023193:web:87bbb7b33cba6fa53a9b48',
    messagingSenderId: '166231023193',
    projectId: 'badminton-d689a',
    authDomain: 'badminton-d689a.firebaseapp.com',
    storageBucket: 'badminton-d689a.firebasestorage.app',
    measurementId: 'G-ZZ7BGS3NFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAiUpqm478bNDA_aiIkvfxh8GWxR40EMc',
    appId: '1:166231023193:android:084a2a82e64eaf4b3a9b48',
    messagingSenderId: '166231023193',
    projectId: 'badminton-d689a',
    storageBucket: 'badminton-d689a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApu5ggXezIqn3HETlTX2eIMyE4N2nIzX8',
    appId: '1:166231023193:ios:9227c4f5f40d306e3a9b48',
    messagingSenderId: '166231023193',
    projectId: 'badminton-d689a',
    storageBucket: 'badminton-d689a.firebasestorage.app',
    androidClientId: '166231023193-eaklba37rdul0gs54rh8plqnateu67t8.apps.googleusercontent.com',
    iosClientId: '166231023193-lb6vp3k02tu965uqcvbd4phm0rhj3j9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.badminton',
  );

}